# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: desc.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndesc.proto\x12\tdiscovery\"0\n\x08NodeInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"@\n\x13RegisterNodeRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"\'\n\x14RegisterNodeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x11\n\x0fGetNodesRequest\"6\n\x10GetNodesResponse\x12\"\n\x05nodes\x18\x01 \x03(\x0b\x32\x13.discovery.NodeInfo2\xa9\x01\n\rNodeDiscovery\x12Q\n\x0cRegisterNode\x12\x1e.discovery.RegisterNodeRequest\x1a\x1f.discovery.RegisterNodeResponse\"\x00\x12\x45\n\x08GetNodes\x12\x1a.discovery.GetNodesRequest\x1a\x1b.discovery.GetNodesResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'desc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NODEINFO']._serialized_start=25
  _globals['_NODEINFO']._serialized_end=73
  _globals['_REGISTERNODEREQUEST']._serialized_start=75
  _globals['_REGISTERNODEREQUEST']._serialized_end=139
  _globals['_REGISTERNODERESPONSE']._serialized_start=141
  _globals['_REGISTERNODERESPONSE']._serialized_end=180
  _globals['_GETNODESREQUEST']._serialized_start=182
  _globals['_GETNODESREQUEST']._serialized_end=199
  _globals['_GETNODESRESPONSE']._serialized_start=201
  _globals['_GETNODESRESPONSE']._serialized_end=255
  _globals['_NODEDISCOVERY']._serialized_start=258
  _globals['_NODEDISCOVERY']._serialized_end=427
# @@protoc_insertion_point(module_scope)
